apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
spec:
  selector:
    app: {{ .Release.Name }}-backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: {{ .Values.backend.service.type }}